# Generated by Django 6.0.6 on 2026-06-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAccuracySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text="Opponent's rating in the game this sample was measured from.")),
                ('accuracy', models.FloatField(help_text="Opponent's measured accuracy (0-100) for that game, from GameEvaluator.")),
                ('time_class', models.CharField(choices=[('bullet', 'Bullet'), ('blitz', 'Blitz'), ('rapid', 'Rapid'), ('classical', 'Classical'), ('daily', 'Daily'), ('correspondence', 'Correspondence'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('platform', models.CharField(choices=[('chess.com', 'Chess.com'), ('lichess', 'Lichess'), ('pgn', 'Uploaded PGN')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['time_class', 'rating'], name='analyzer_ra_time_cl_6805ed_idx')],
            },
        ),
    ]
